baseURL = "https://JohnNadja.xyz/My-LaunchX-BackEnd-Blog/"
languageCode = "en-us"
title = "BitÃ¡cora de Viaje Jonathan Ovando SÃ¡nchez"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "@stry_john"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
